Use g++-8 needed for c++ stdlib filesystem
Without this, the following error occurred.
```
libtool: compile:  c++ -DHAVE_CONFIG_H -I. -I../include -Dlinux -D_LARGEFILE64_SOURCE=1 -D_COMPILE64BIT_SOURCE=1 -D_REENTRANT -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -I/<<PKGBUILDDIR>>/proxy/api -I/<<PKGBUILDDIR>>/proxy/api -I/<<PKGBUILDDIR>>/include/cppapi/include -I/<<PKGBUILDDIR>>/lib/cppapi/include -I/<<PKGBUILDDIR>>/include -I/<<PKGBUILDDIR>>/lib -I/<<PKGBUILDDIR>>/lib/yamlcpp/include -I/<<PKGBUILDDIR>>/lib/yamlcpp/include -I/<<PKGBUILDDIR>>/lib/yamlcpp/include -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -DOPENSSL_NO_SSL_INTERN -I/usr/include/include -std=c++17 -g -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -feliminate-unused-debug-symbols -fno-strict-aliasing -Wno-invalid-offsetof -Wno-noexcept-type -Wsuggest-override -mcx16 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -O3 -c experimental/statichit/statichit.cc  -fPIC -DPIC -o experimental/statichit/.libs/statichit.o
experimental/statichit/statichit.cc:36:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
```